image:
  - macOS
  - Ubuntu
  - Visual Studio 2019

for:
-
  matrix:
    only:
      - image: Visual Studio 2019

  init:
    ps: |
          $ErrorActionPreference = "Stop"
          Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
          Import-Module '..\appveyor-tool.ps1'

  install:
    ps: Bootstrap

  cache:
    - C:\RLibrary

  build_script:
    - set PATH=%PATH:C:\MinGW\msys\1.0\bin;=%
    - echo | tools\install-windows.bat
    - Rscript -e "update.packages(ask = FALSE, checkBuilt = TRUE, repos = 'https://cran.rstudio.com')"

  before_test:
    - choco install pandoc --version 2.7.3
    - pandoc -v

  test_script:
    - set PATH=%APPDATA%\TinyTeX\bin\win32;%PATH%
    - travis-tool.sh install_deps
    - R CMD INSTALL .
    - Rscript "tools/test-basic.R"
    - 7z a TinyTeX.zip %APPDATA%\\TinyTeX
    - travis-tool.sh run_tests
    - Rscript -e "tinytex::install_tinytex(force = TRUE)"

  artifacts:
    - path: TinyTeX.zip
      name: TinyTeX

-
  matrix:
    only:
      - image: macOS

  cache:
    - $HOME/R

  install:
    - brew install pandoc pandoc-citeproc p7zip
    - brew cask install r
    - echo 'options(repos = "https://cran.rstudio.com")' > ~/.Rprofile
    - mkdir -p ~/R
    - echo 'R_LIBS_USER="~/R"' > ~/.Renviron
    - Rscript -e "install.packages('tinytex', dependencies = TRUE)"
    - R CMD INSTALL .

  build_script:
    - ./tools/install-unx.sh

  test_script:
    - Rscript "tools/test-basic.R"
    - tar zcf TinyTeX.tgz -C ~/Library TinyTeX

  artifacts:
    - path: TinyTeX.tgz
      name: TinyTeX

-
  matrix:
    only:
      - image: Ubuntu

  cache:
    - $HOME/R

  install:
    - sudo apt -y update
    - sudo apt -y install r-base-dev pandoc pandoc-citeproc
    - echo 'options(repos = "https://cran.rstudio.com")' > ~/.Rprofile
    - mkdir -p ~/R
    - echo 'R_LIBS_USER="~/R"' > ~/.Renviron
    - Rscript -e "install.packages('tinytex', dependencies = TRUE)"
    - R CMD INSTALL .

  build_script:
    - ./tools/install-unx.sh

  test_script:
    - Rscript "tools/test-basic.R"
    - tar zcf TinyTeX.tar.gz -C ~ .TinyTeX

  artifacts:
    - path: TinyTeX.tar.gz
      name: TinyTeX
