environment:
  PATH: "%APPDATA%\\TinyTeX\\bin\\win32;%PATH%"

build_script:
  - echo | tools\install-windows.bat

test_script:
  - tlmgr --version
  - pdflatex --version
  - xelatex --version
  - 7z a TinyTeX.zip %APPDATA%\\TinyTeX

artifacts:
  - path: TinyTeX.zip
    name: TinyTeX
