environment:
  PATH: "%APPDATA%\\TinyTeX\\bin\\win32;%PATH%"

init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'

cache:
  - C:\RLibrary

build_script:
  - echo | tools\install-windows.bat

test_script:
  - tlmgr --version
  - pdflatex --version
  - xelatex --version
  - 7z a TinyTeX.zip %APPDATA%\\TinyTeX

artifacts:
  - path: TinyTeX.zip
    name: TinyTeX
